<?php

/**
* Implements hook_theme().
*/
function map_location_block_theme($existing, $type, $theme, $path) {
  return [
    'map_location_block' => []
  ];
}

/**
 * Implements hook_library_info_build().
 */
function map_location_block_library_info_build() {
  $libraries = [];
  $libraries['google_map_api'] = [
    'js' => [
      '//maps.google.com/maps/api/js?key=' . $_ENV['GOOGLE_API_KEY'] => [],
    ],
  ];
  return $libraries;
}