<?php

/**
 * @file
 * Functions to support theming in the theme.
 */

/**
* Implements hook_preprocess_HOOK() for menu.html.twig.
*/
function doghouse_pets_preprocess_menu(&$variables) {
  if ($variables['menu_name'] == 'main') {
    if (!isset($variables['attributes']['class'])) {
      $variables['attributes']['class'] = [];
    }
    $variables['attributes']['class'][] = 'js-menu--main';  
  }
}